package com.example.marketplace.data.dto;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.marketplace.data.converter.LocalDateTimeConverter;
import com.example.marketplace.data.gateway.OrderGateway;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = OrderGateway.TABLE_NAME)
public class OrderDTO {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private List<ProductDTO> products;

    @DynamoDBAttribute
    private CustomerDTO customer;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @DynamoDBAttribute
    private LocalDateTime dateTime;
}
